export interface Doctor {
  id: number
  name: string
  name_ar?: string
  name_tr?: string
  department: string
  department_ar?: string
  department_tr?: string
  building: string
  floor: string
  room: string
  office_hours: string
  email: string
  phone: string
  faculty: string
  faculty_ar?: string
  faculty_tr?: string
}

export interface Building {
  id: string
  name: string
  type: string
  location: string
  floors: number
  hours: string
  departments: string[]
  description: string
  gridPosition: {
    colStart: number
    rowStart: number
    colSpan: number
    rowSpan: number
  }
  color: string
  icon: string
}

export interface Facility {
  id: number
  name: string
  type: string
  location: string
  hours: string
  description: string
}

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Ayşe Öztürk",
    name_ar: "د. عائشة أوزتورك",
    name_tr: "Dr. Ayşe Öztürk",
    department: "Computer Engineering",
    department_ar: "هندسة الحاسوب",
    department_tr: "Bilgisayar Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "2",
    room: "204",
    office_hours: "Mon–Thu 10:00–12:00",
    email: "ayse.ozturk@neu.edu.tr",
    phone: "+90 392 223 6001",
  },
  {
    id: 2,
    name: "Dr. Kerem Aydın",
    name_ar: "د. كريم أيدن",
    name_tr: "Dr. Kerem Aydın",
    department: "Electrical Engineering",
    department_ar: "الهندسة الكهربائية",
    department_tr: "Elektrik Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "1",
    room: "116",
    office_hours: "Wed–Fri 09:00–11:00",
    email: "kerem.aydin@neu.edu.tr",
    phone: "+90 392 223 6006",
  },
  {
    id: 3,
    name: "Dr. Ceren İlhan",
    name_ar: "د. سيرين إلهان",
    name_tr: "Dr. Ceren İlhan",
    department: "Mechanical Engineering",
    department_ar: "الهندسة الميكانيكية",
    department_tr: "Makine Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "3",
    room: "309",
    office_hours: "Mon–Wed 14:00–16:00",
    email: "ceren.ilhan@neu.edu.tr",
    phone: "+90 392 223 6013",
  },
  {
    id: 4,
    name: "Dr. Taha Şahin",
    name_ar: "د. طه شاهين",
    name_tr: "Dr. Taha Şahin",
    department: "Software Engineering",
    department_ar: "هندسة البرمجيات",
    department_tr: "Yazılım Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "1",
    room: "118",
    office_hours: "Tue–Thu 09:00–11:00",
    email: "taha.sahin@neu.edu.tr",
    phone: "+90 392 223 6014",
  },
  {
    id: 5,
    name: "Dr. Bilal Arslan",
    name_ar: "د. بلال أرسلان",
    name_tr: "Dr. Bilal Arslan",
    department: "Artificial Intelligence",
    department_ar: "الذكاء الاصطناعي",
    department_tr: "Yapay Zeka",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "2",
    room: "205",
    office_hours: "Wed–Fri 10:00–12:00",
    email: "bilal.arslan@neu.edu.tr",
    phone: "+90 392 223 6015",
  },
  {
    id: 6,
    name: "Dr. Rana Aksoy",
    name_ar: "د. رنا أكسوي",
    name_tr: "Dr. Rana Aksoy",
    department: "Civil Engineering",
    department_ar: "الهندسة المدنية",
    department_tr: "İnşaat Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Block B",
    floor: "2",
    room: "221",
    office_hours: "Mon–Thu 14:00–16:00",
    email: "rana.aksoy@neu.edu.tr",
    phone: "+90 392 223 6007",
  },
  {
    id: 7,
    name: "Dr. Emre Yılmaz",
    name_ar: "د. إمري يلماز",
    name_tr: "Dr. Emre Yılmaz",
    department: "Industrial Engineering",
    department_ar: "الهندسة الصناعية",
    department_tr: "Endüstri Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "3",
    room: "315",
    office_hours: "Tue–Fri 11:00–13:00",
    email: "emre.yilmaz@neu.edu.tr",
    phone: "+90 392 223 6016",
  },
  {
    id: 8,
    name: "Dr. Zeynep Acar",
    name_ar: "د. زينب أجار",
    name_tr: "Dr. Zeynep Acar",
    department: "Biomedical Engineering",
    department_ar: "الهندسة الطبية الحيوية",
    department_tr: "Biyomedikal Mühendislik",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Faculty",
    floor: "2",
    room: "218",
    office_hours: "Mon–Wed 10:00–12:00",
    email: "zeynep.acar@neu.edu.tr",
    phone: "+90 392 223 6017",
  },
  {
    id: 9,
    name: "Dr. Burak Çelik",
    name_ar: "د. بوراك تشيليك",
    name_tr: "Dr. Burak Çelik",
    department: "Chemical Engineering",
    department_ar: "الهندسة الكيميائية",
    department_tr: "Kimya Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Block B",
    floor: "1",
    room: "105",
    office_hours: "Wed–Fri 13:00–15:00",
    email: "burak.celik@neu.edu.tr",
    phone: "+90 392 223 6018",
  },
  {
    id: 10,
    name: "Dr. Deniz Koç",
    name_ar: "د. دينيز كوتش",
    name_tr: "Dr. Deniz Koç",
    department: "Environmental Engineering",
    department_ar: "الهندسة البيئية",
    department_tr: "Çevre Mühendisliği",
    faculty: "Engineering Faculty",
    faculty_ar: "كلية الهندسة",
    faculty_tr: "Mühendislik Fakültesi",
    building: "Engineering Block B",
    floor: "3",
    room: "305",
    office_hours: "Mon–Thu 09:00–11:00",
    email: "deniz.koc@neu.edu.tr",
    phone: "+90 392 223 6019",
  },
  {
    id: 11,
    name: "Dr. Ali Demir",
    name_ar: "د. علي ديمير",
    name_tr: "Dr. Ali Demir",
    department: "Internal Medicine",
    department_ar: "الطب الباطني",
    department_tr: "İç Hastalıkları",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "3",
    room: "312",
    office_hours: "Tue–Fri 09:00–11:00",
    email: "ali.demir@neu.edu.tr",
    phone: "+90 392 223 6002",
  },
  {
    id: 12,
    name: "Dr. Mehmet Kaya",
    name_ar: "د. محمد كايا",
    name_tr: "Dr. Mehmet Kaya",
    department: "Surgery",
    department_ar: "الجراحة",
    department_tr: "Cerrahi",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "4",
    room: "408",
    office_hours: "Mon–Wed 13:00–15:00",
    email: "mehmet.kaya@neu.edu.tr",
    phone: "+90 392 223 6003",
  },
  {
    id: 13,
    name: "Dr. Elif Şen",
    name_ar: "د. إليف شين",
    name_tr: "Dr. Elif Şen",
    department: "Cardiology",
    department_ar: "أمراض القلب",
    department_tr: "Kardiyoloji",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "3",
    room: "320",
    office_hours: "Tue–Thu 10:00–12:00",
    email: "elif.sen@neu.edu.tr",
    phone: "+90 392 223 6020",
  },
  {
    id: 14,
    name: "Dr. Ahmet Yurt",
    name_ar: "د. أحمد يورت",
    name_tr: "Dr. Ahmet Yurt",
    department: "Neurology",
    department_ar: "طب الأعصاب",
    department_tr: "Nöroloji",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "5",
    room: "512",
    office_hours: "Mon–Fri 09:00–11:00",
    email: "ahmet.yurt@neu.edu.tr",
    phone: "+90 392 223 6021",
  },
  {
    id: 15,
    name: "Dr. Seda Özkan",
    name_ar: "د. سيدا أوزكان",
    name_tr: "Dr. Seda Özkan",
    department: "Pediatrics",
    department_ar: "طب الأطفال",
    department_tr: "Pediatri",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "2",
    room: "215",
    office_hours: "Wed–Fri 13:00–15:00",
    email: "seda.ozkan@neu.edu.tr",
    phone: "+90 392 223 6022",
  },
  {
    id: 16,
    name: "Dr. Can Arslan",
    name_ar: "د. جان أرسلان",
    name_tr: "Dr. Can Arslan",
    department: "Orthopedics",
    department_ar: "جراحة العظام",
    department_tr: "Ortopedi",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "4",
    room: "415",
    office_hours: "Mon–Thu 10:00–12:00",
    email: "can.arslan@neu.edu.tr",
    phone: "+90 392 223 6023",
  },
  {
    id: 17,
    name: "Dr. Gizem Yıldız",
    name_ar: "د. جيزيم يلدز",
    name_tr: "Dr. Gizem Yıldız",
    department: "Radiology",
    department_ar: "الأشعة",
    department_tr: "Radyoloji",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "1",
    room: "118",
    office_hours: "Tue–Fri 11:00–13:00",
    email: "gizem.yildiz@neu.edu.tr",
    phone: "+90 392 223 6024",
  },
  {
    id: 18,
    name: "Dr. Cem Kara",
    name_ar: "د. جيم قره",
    name_tr: "Dr. Cem Kara",
    department: "Psychiatry",
    department_ar: "الطب النفسي",
    department_tr: "Psikiyatri",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "5",
    room: "520",
    office_hours: "Mon–Wed 14:00–16:00",
    email: "cem.kara@neu.edu.tr",
    phone: "+90 392 223 6025",
  },
  {
    id: 19,
    name: "Dr. Aylin Erdoğan",
    name_ar: "د. أيلين أردوغان",
    name_tr: "Dr. Aylin Erdoğan",
    department: "Dermatology",
    department_ar: "الأمراض الجلدية",
    department_tr: "Dermatoloji",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "2",
    room: "220",
    office_hours: "Wed–Fri 09:00–11:00",
    email: "aylin.erdogan@neu.edu.tr",
    phone: "+90 392 223 6026",
  },
  {
    id: 20,
    name: "Dr. Onur Tekin",
    name_ar: "د. أونور تكين",
    name_tr: "Dr. Onur Tekin",
    department: "Ophthalmology",
    department_ar: "طب العيون",
    department_tr: "Göz Hastalıkları",
    faculty: "Faculty of Medicine",
    faculty_ar: "كلية الطب",
    faculty_tr: "Tıp Fakültesi",
    building: "Medical Faculty",
    floor: "3",
    room: "325",
    office_hours: "Mon–Thu 13:00–15:00",
    email: "onur.tekin@neu.edu.tr",
    phone: "+90 392 223 6027",
  },
  {
    id: 21,
    name: "Dr. Mehmet Kaya",
    name_ar: "د. محمد كايا",
    name_tr: "Dr. Mehmet Kaya",
    department: "General Dentistry",
    department_ar: "طب الأسنان العام",
    department_tr: "Genel Diş Hekimliği",
    faculty: "Dentistry Faculty",
    faculty_ar: "كلية طب الأسنان",
    faculty_tr: "Diş Hekimliği Fakültesi",
    building: "Dentistry Faculty",
    floor: "1",
    room: "108",
    office_hours: "Mon–Wed 13:00–15:00",
    email: "mehmet.kaya@neu.edu.tr",
    phone: "+90 392 223 6003",
  },
  {
    id: 22,
    name: "Dr. Leyla Koçak",
    name_ar: "د. ليلى كوتشاك",
    name_tr: "Dr. Leyla Koçak",
    department: "Orthodontics",
    department_ar: "تقويم الأسنان",
    department_tr: "Ortodonti",
    faculty: "Dentistry Faculty",
    faculty_ar: "كلية طب الأسنان",
    faculty_tr: "Diş Hekimliği Fakültesi",
    building: "Dentistry Faculty",
    floor: "2",
    room: "205",
    office_hours: "Tue–Thu 10:00–12:00",
    email: "leyla.kocak@neu.edu.tr",
    phone: "+90 392 223 6028",
  },
  {
    id: 23,
    name: "Dr. Serkan Aydın",
    name_ar: "د. سيركان أيدن",
    name_tr: "Dr. Serkan Aydın",
    department: "Oral Surgery",
    department_ar: "جراحة الفم",
    department_tr: "Ağız Cerrahisi",
    faculty: "Dentistry Faculty",
    faculty_ar: "كلية طب الأسنان",
    faculty_tr: "Diş Hekimliği Fakültesi",
    building: "Dentistry Faculty",
    floor: "2",
    room: "212",
    office_hours: "Mon–Fri 09:00–11:00",
    email: "serkan.aydin@neu.edu.tr",
    phone: "+90 392 223 6029",
  },
  {
    id: 24,
    name: "Dr. Pınar Güven",
    name_ar: "د. بنار غوفين",
    name_tr: "Dr. Pınar Güven",
    department: "Pediatric Dentistry",
    department_ar: "طب أسنان الأطفال",
    department_tr: "Pedodonti",
    faculty: "Dentistry Faculty",
    faculty_ar: "كلية طب الأسنان",
    faculty_tr: "Diş Hekimliği Fakültesi",
    building: "Dentistry Faculty",
    floor: "1",
    room: "115",
    office_hours: "Wed–Fri 13:00–15:00",
    email: "pinar.guven@neu.edu.tr",
    phone: "+90 392 223 6030",
  },
  {
    id: 25,
    name: "Dr. Tolga Akar",
    name_ar: "د. تولغا أكار",
    name_tr: "Dr. Tolga Akar",
    department: "Prosthodontics",
    department_ar: "تركيبات الأسنان",
    department_tr: "Protetik Diş Tedavisi",
    faculty: "Dentistry Faculty",
    faculty_ar: "كلية طب الأسنان",
    faculty_tr: "Diş Hekimliği Fakültesi",
    building: "Dentistry Faculty",
    floor: "3",
    room: "310",
    office_hours: "Mon–Thu 10:00–12:00",
    email: "tolga.akar@neu.edu.tr",
    phone: "+90 392 223 6031",
  },
  {
    id: 26,
    name: "Dr. Selin Yıldız",
    name_ar: "د. سيلين يلدز",
    name_tr: "Dr. Selin Yıldız",
    department: "Clinical Pharmacy",
    department_ar: "الصيدلة السريرية",
    department_tr: "Klinik Eczacılık",
    faculty: "Pharmacy Faculty",
    faculty_ar: "كلية الصيدلة",
    faculty_tr: "Eczacılık Fakültesi",
    building: "Pharmacy Faculty",
    floor: "2",
    room: "215",
    office_hours: "Tue–Thu 10:00–12:00",
    email: "selin.yildiz@neu.edu.tr",
    phone: "+90 392 223 6004",
  },
  {
    id: 27,
    name: "Dr. Hasan Polat",
    name_ar: "د. حسن بولات",
    name_tr: "Dr. Hasan Polat",
    department: "Pharmaceutical Chemistry",
    department_ar: "الكيمياء الصيدلانية",
    department_tr: "Farmasötik Kimya",
    faculty: "Pharmacy Faculty",
    faculty_ar: "كلية الصيدلة",
    faculty_tr: "Eczacılık Fakültesi",
    building: "Pharmacy Faculty",
    floor: "3",
    room: "318",
    office_hours: "Mon–Wed 11:00–13:00",
    email: "hasan.polat@neu.edu.tr",
    phone: "+90 392 223 6032",
  },
  {
    id: 28,
    name: "Dr. İrem Kılıç",
    name_ar: "د. إيريم كيليتش",
    name_tr: "Dr. İrem Kılıç",
    department: "Pharmacology",
    department_ar: "علم الأدوية",
    department_tr: "Farmakoloji",
    faculty: "Pharmacy Faculty",
    faculty_ar: "كلية الصيدلة",
    faculty_tr: "Eczacılık Fakültesi",
    building: "Pharmacy Faculty",
    floor: "2",
    room: "220",
    office_hours: "Wed–Fri 09:00–11:00",
    email: "irem.kilic@neu.edu.tr",
    phone: "+90 392 223 6033",
  },
  {
    id: 29,
    name: "Dr. Kaan Demir",
    name_ar: "د. كان ديمير",
    name_tr: "Dr. Kaan Demir",
    department: "Pharmaceutical Technology",
    department_ar: "التكنولوجيا الصيدلانية",
    department_tr: "Farmasötik Teknoloji",
    faculty: "Pharmacy Faculty",
    faculty_ar: "كلية الصيدلة",
    faculty_tr: "Eczacılık Fakültesi",
    building: "Pharmacy Faculty",
    floor: "1",
    room: "112",
    office_hours: "Mon–Thu 14:00–16:00",
    email: "kaan.demir@neu.edu.tr",
    phone: "+90 392 223 6034",
  },
  {
    id: 30,
    name: "Dr. Neslihan Öz",
    name_ar: "د. نسليهان أوز",
    name_tr: "Dr. Neslihan Öz",
    department: "Pharmaceutical Botany",
    department_ar: "النباتات الطبية",
    department_tr: "Farmakognozi",
    faculty: "Pharmacy Faculty",
    faculty_ar: "كلية الصيدلة",
    faculty_tr: "Eczacılık Fakültesi",
    building: "Pharmacy Faculty",
    floor: "3",
    room: "305",
    office_hours: "Tue–Fri 10:00–12:00",
    email: "neslihan.oz@neu.edu.tr",
    phone: "+90 392 223 6035",
  },
  {
    id: 31,
    name: "Dr. Fatma Erkan",
    name_ar: "د. فاطمة إركان",
    name_tr: "Dr. Fatma Erkan",
    department: "Architecture Design",
    department_ar: "تصميم العمارة",
    department_tr: "Mimari Tasarım",
    faculty: "Architecture Faculty",
    faculty_ar: "كلية العمارة",
    faculty_tr: "Mimarlık Fakültesi",
    building: "Architecture Faculty",
    floor: "3",
    room: "302",
    office_hours: "Mon–Fri 11:00–13:00",
    email: "fatma.erkan@neu.edu.tr",
    phone: "+90 392 223 6005",
  },
  {
    id: 32,
    name: "Dr. Mert Yaman",
    name_ar: "د. ميرت يامان",
    name_tr: "Dr. Mert Yaman",
    department: "Urban Planning",
    department_ar: "التخطيط الحضري",
    department_tr: "Şehir Planlama",
    faculty: "Architecture Faculty",
    faculty_ar: "كلية العمارة",
    faculty_tr: "Mimarlık Fakültesi",
    building: "Architecture Faculty",
    floor: "2",
    room: "210",
    office_hours: "Tue–Thu 13:00–15:00",
    email: "mert.yaman@neu.edu.tr",
    phone: "+90 392 223 6036",
  },
  {
    id: 33,
    name: "Dr. Esra Duman",
    name_ar: "د. إسراء دومان",
    name_tr: "Dr. Esra Duman",
    department: "Interior Design",
    department_ar: "التصميم الداخلي",
    department_tr: "İç Mimarlık",
    faculty: "Architecture Faculty",
    faculty_ar: "كلية العمارة",
    faculty_tr: "Mimarlık Fakültesi",
    building: "Architecture Faculty",
    floor: "1",
    room: "115",
    office_hours: "Mon–Wed 10:00–12:00",
    email: "esra.duman@neu.edu.tr",
    phone: "+90 392 223 6037",
  },
  {
    id: 34,
    name: "Dr. Barış Öner",
    name_ar: "د. باريش أونير",
    name_tr: "Dr. Barış Öner",
    department: "Landscape Architecture",
    department_ar: "هندسة المناظر الطبيعية",
    department_tr: "Peyzaj Mimarlığı",
    faculty: "Architecture Faculty",
    faculty_ar: "كلية العمارة",
    faculty_tr: "Mimarlık Fakültesi",
    building: "Architecture Faculty",
    floor: "2",
    room: "225",
    office_hours: "Wed–Fri 14:00–16:00",
    email: "baris.oner@neu.edu.tr",
    phone: "+90 392 223 6038",
  },
  {
    id: 35,
    name: "Dr. Sinem Uysal",
    name_ar: "د. سينم أويسال",
    name_tr: "Dr. Sinem Uysal",
    department: "Building Materials",
    department_ar: "مواد البناء",
    department_tr: "Yapı Malzemeleri",
    faculty: "Architecture Faculty",
    faculty_ar: "كلية العمارة",
    faculty_tr: "Mimarlık Fakültesi",
    building: "Architecture Faculty",
    floor: "3",
    room: "320",
    office_hours: "Mon–Thu 09:00–11:00",
    email: "sinem.uysal@neu.edu.tr",
    phone: "+90 392 223 6039",
  },
  {
    id: 36,
    name: "Dr. Yusuf Çetin",
    name_ar: "د. يوسف تشيتين",
    name_tr: "Dr. Yusuf Çetin",
    department: "Business Administration",
    department_ar: "إدارة الأعمال",
    department_tr: "İşletme Yönetimi",
    faculty: "Economics & Business Faculty",
    faculty_ar: "كلية الاقتصاد والإدارة",
    faculty_tr: "İktisat ve İdari Bilimler Fakültesi",
    building: "Economics Faculty",
    floor: "1",
    room: "112",
    office_hours: "Tue–Thu 10:00–12:00",
    email: "yusuf.cetin@neu.edu.tr",
    phone: "+90 392 223 6008",
  },
  {
    id: 37,
    name: "Dr. Hakan Dursun",
    name_ar: "د. حاكان دورسون",
    name_tr: "Dr. Hakan Dursun",
    department: "Economics",
    department_ar: "الاقتصاد",
    department_tr: "İktisat",
    faculty: "Economics & Business Faculty",
    faculty_ar: "كلية الاقتصاد والإدارة",
    faculty_tr: "İktisat ve İdari Bilimler Fakültesi",
    building: "Economics Faculty",
    floor: "2",
    room: "210",
    office_hours: "Wed–Fri 13:00–15:00",
    email: "hakan.dursun@neu.edu.tr",
    phone: "+90 392 223 6010",
  },
  {
    id: 38,
    name: "Dr. Merve Şeker",
    name_ar: "د. ميرفي شيكير",
    name_tr: "Dr. Merve Şeker",
    department: "Finance & Banking",
    department_ar: "المالية والمصرفية",
    department_tr: "Finans ve Bankacılık",
    faculty: "Economics & Business Faculty",
    faculty_ar: "كلية الاقتصاد والإدارة",
    faculty_tr: "İktisat ve İdari Bilimler Fakültesi",
    building: "Economics Faculty",
    floor: "3",
    room: "315",
    office_hours: "Mon–Thu 11:00–13:00",
    email: "merve.seker@neu.edu.tr",
    phone: "+90 392 223 6040",
  },
  {
    id: 39,
    name: "Dr. Okan Taş",
    name_ar: "د. أوكان طاش",
    name_tr: "Dr. Okan Taş",
    department: "Marketing",
    department_ar: "التسويق",
    department_tr: "Pazarlama",
    faculty: "Economics & Business Faculty",
    faculty_ar: "كلية الاقتصاد والإدارة",
    faculty_tr: "İktisat ve İdari Bilimler Fakültesi",
    building: "Economics Faculty",
    floor: "1",
    room: "120",
    office_hours: "Tue–Fri 09:00–11:00",
    email: "okan.tas@neu.edu.tr",
    phone: "+90 392 223 6041",
  },
  {
    id: 40,
    name: "Dr. Ece Yavuz",
    name_ar: "د. إيجي يافوز",
    name_tr: "Dr. Ece Yavuz",
    department: "Accounting",
    department_ar: "المحاسبة",
    department_tr: "Muhasebe",
    faculty: "Economics & Business Faculty",
    faculty_ar: "كلية الاقتصاد والإدارة",
    faculty_tr: "İktisat ve İdari Bilimler Fakültesi",
    building: "Economics Faculty",
    floor: "2",
    room: "225",
    office_hours: "Mon–Wed 14:00–16:00",
    email: "ece.yavuz@neu.edu.tr",
    phone: "+90 392 223 6042",
  },
  {
    id: 41,
    name: "Dr. Selim Kurt",
    name_ar: "د. سليم كورت",
    name_tr: "Dr. Selim Kurt",
    department: "International Trade",
    department_ar: "التجارة الدولية",
    department_tr: "Uluslararası Ticaret",
    faculty: "Economics & Business Faculty",
    faculty_ar: "كلية الاقتصاد والإدارة",
    faculty_tr: "İktisat ve İdari Bilimler Fakültesi",
    building: "Economics Faculty",
    floor: "3",
    room: "308",
    office_hours: "Wed–Fri 10:00–12:00",
    email: "selim.kurt@neu.edu.tr",
    phone: "+90 392 223 6043",
  },
  {
    id: 42,
    name: "Dr. Emine Karaca",
    name_ar: "د. إيمينه قره جا",
    name_tr: "Dr. Emine Karaca",
    department: "Constitutional Law",
    department_ar: "القانون الدستوري",
    department_tr: "Anayasa Hukuku",
    faculty: "Law Faculty",
    faculty_ar: "كلية الحقوق",
    faculty_tr: "Hukuk Fakültesi",
    building: "Law Faculty",
    floor: "3",
    room: "305",
    office_hours: "Mon–Wed 09:00–11:00",
    email: "emine.karaca@neu.edu.tr",
    phone: "+90 392 223 6009",
  },
  {
    id: 43,
    name: "Dr. Volkan Ay",
    name_ar: "د. فولكان آي",
    name_tr: "Dr. Volkan Ay",
    department: "Criminal Law",
    department_ar: "القانون الجنائي",
    department_tr: "Ceza Hukuku",
    faculty: "Law Faculty",
    faculty_ar: "كلية الحقوق",
    faculty_tr: "Hukuk Fakültesi",
    building: "Law Faculty",
    floor: "2",
    room: "218",
    office_hours: "Tue–Thu 13:00–15:00",
    email: "volkan.ay@neu.edu.tr",
    phone: "+90 392 223 6044",
  },
  {
    id: 44,
    name: "Dr. Dilek Aslan",
    name_ar: "د. ديليك أسلان",
    name_tr: "Dr. Dilek Aslan",
    department: "Civil Law",
    department_ar: "القانون المدني",
    department_tr: "Medeni Hukuk",
    faculty: "Law Faculty",
    faculty_ar: "كلية الحقوق",
    faculty_tr: "Hukuk Fakültesi",
    building: "Law Faculty",
    floor: "1",
    room: "110",
    office_hours: "Mon–Fri 10:00–12:00",
    email: "dilek.aslan@neu.edu.tr",
    phone: "+90 392 223 6045",
  },
  {
    id: 45,
    name: "Dr. Emre Başaran",
    name_ar: "د. إمري باشاران",
    name_tr: "Dr. Emre Başaran",
    department: "International Law",
    department_ar: "القانون الدولي",
    department_tr: "Uluslararası Hukuk",
    faculty: "Law Faculty",
    faculty_ar: "كلية الحقوق",
    faculty_tr: "Hukuk Fakültesi",
    building: "Law Faculty",
    floor: "3",
    room: "320",
    office_hours: "Wed–Fri 11:00–13:00",
    email: "emre.basaran@neu.edu.tr",
    phone: "+90 392 223 6046",
  },
  {
    id: 46,
    name: "Dr. Burcu Çakır",
    name_ar: "د. بورجو تشاكر",
    name_tr: "Dr. Burcu Çakır",
    department: "Commercial Law",
    department_ar: "القانون التجاري",
    department_tr: "Ticaret Hukuku",
    faculty: "Law Faculty",
    faculty_ar: "كلية الحقوق",
    faculty_tr: "Hukuk Fakültesi",
    building: "Law Faculty",
    floor: "2",
    room: "205",
    office_hours: "Mon–Thu 14:00–16:00",
    email: "burcu.cakir@neu.edu.tr",
    phone: "+90 392 223 6047",
  },
  {
    id: 47,
    name: "Dr. Sibel Güler",
    name_ar: "د. سيبل غولير",
    name_tr: "Dr. Sibel Güler",
    department: "Psychology",
    department_ar: "علم النفس",
    department_tr: "Psikoloji",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "1",
    room: "122",
    office_hours: "Mon–Thu 10:00–12:00",
    email: "sibel.guler@neu.edu.tr",
    phone: "+90 392 223 6011",
  },
  {
    id: 48,
    name: "Dr. Murat Özkan",
    name_ar: "د. مراد أوزكان",
    name_tr: "Dr. Murat Özkan",
    department: "Mathematics",
    department_ar: "الرياضيات",
    department_tr: "Matematik",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "2",
    room: "216",
    office_hours: "Tue–Fri 11:00–13:00",
    email: "murat.ozkan@neu.edu.tr",
    phone: "+90 392 223 6012",
  },
  {
    id: 49,
    name: "Dr. Tuğba Yavuz",
    name_ar: "د. توغبا يافوز",
    name_tr: "Dr. Tuğba Yavuz",
    department: "English Literature",
    department_ar: "الأدب الإنجليزي",
    department_tr: "İngiliz Dili ve Edebiyatı",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "3",
    room: "310",
    office_hours: "Mon–Wed 13:00–15:00",
    email: "tugba.yavuz@neu.edu.tr",
    phone: "+90 392 223 6048",
  },
  {
    id: 50,
    name: "Dr. Ufuk Özmen",
    name_ar: "د. أوفوك أوزمن",
    name_tr: "Dr. Ufuk Özmen",
    department: "Physics",
    department_ar: "الفيزياء",
    department_tr: "Fizik",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "2",
    room: "220",
    office_hours: "Wed–Fri 09:00–11:00",
    email: "ufuk.ozmen@neu.edu.tr",
    phone: "+90 392 223 6049",
  },
  {
    id: 51,
    name: "Dr. İpek Tunç",
    name_ar: "د. إيبيك تونتش",
    name_tr: "Dr. İpek Tunç",
    department: "Chemistry",
    department_ar: "الكيمياء",
    department_tr: "Kimya",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "1",
    room: "115",
    office_hours: "Mon–Thu 14:00–16:00",
    email: "ipek.tunc@neu.edu.tr",
    phone: "+90 392 223 6050",
  },
  {
    id: 52,
    name: "Dr. Alper Güneş",
    name_ar: "د. ألبير غونيش",
    name_tr: "Dr. Alper Güneş",
    department: "Biology",
    department_ar: "علم الأحياء",
    department_tr: "Biyoloji",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "3",
    room: "325",
    office_hours: "Tue–Fri 10:00–12:00",
    email: "alper.gunes@neu.edu.tr",
    phone: "+90 392 223 6051",
  },
  {
    id: 53,
    name: "Dr. Gamze Akgül",
    name_ar: "د. غامزي أكغول",
    name_tr: "Dr. Gamze Akgül",
    department: "History",
    department_ar: "التاريخ",
    department_tr: "Tarih",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "2",
    room: "208",
    office_hours: "Mon–Wed 11:00–13:00",
    email: "gamze.akgul@neu.edu.tr",
    phone: "+90 392 223 6052",
  },
  {
    id: 54,
    name: "Dr. Kemal Eren",
    name_ar: "د. كمال إيرين",
    name_tr: "Dr. Kemal Eren",
    department: "Sociology",
    department_ar: "علم الاجتماع",
    department_tr: "Sosyoloji",
    faculty: "Arts & Sciences Faculty",
    faculty_ar: "كلية الآداب والعلوم",
    faculty_tr: "Fen-Edebiyat Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "1",
    room: "128",
    office_hours: "Wed–Fri 13:00–15:00",
    email: "kemal.eren@neu.edu.tr",
    phone: "+90 392 223 6053",
  },
  {
    id: 55,
    name: "Dr. Şebnem Taş",
    name_ar: "د. شبنم طاش",
    name_tr: "Dr. Şebnem Taş",
    department: "Journalism",
    department_ar: "الصحافة",
    department_tr: "Gazetecilik",
    faculty: "Communication Faculty",
    faculty_ar: "كلية الاتصال",
    faculty_tr: "İletişim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "3",
    room: "330",
    office_hours: "Mon–Thu 09:00–11:00",
    email: "sebnem.tas@neu.edu.tr",
    phone: "+90 392 223 6054",
  },
  {
    id: 56,
    name: "Dr. Levent Öztürk",
    name_ar: "د. ليفينت أوزتورك",
    name_tr: "Dr. Levent Öztürk",
    department: "Public Relations",
    department_ar: "العلاقات العامة",
    department_tr: "Halkla İlişkiler",
    faculty: "Communication Faculty",
    faculty_ar: "كلية الاتصال",
    faculty_tr: "İletişim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "2",
    room: "230",
    office_hours: "Tue–Fri 10:00–12:00",
    email: "levent.ozturk@neu.edu.tr",
    phone: "+90 392 223 6055",
  },
  {
    id: 57,
    name: "Dr. Ayça Demir",
    name_ar: "د. أيتشا ديمير",
    name_tr: "Dr. Ayça Demir",
    department: "Radio & Television",
    department_ar: "الإذاعة والتلفزيون",
    department_tr: "Radyo ve Televizyon",
    faculty: "Communication Faculty",
    faculty_ar: "كلية الاتصال",
    faculty_tr: "İletişim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "1",
    room: "135",
    office_hours: "Mon–Wed 13:00–15:00",
    email: "ayca.demir@neu.edu.tr",
    phone: "+90 392 223 6056",
  },
  {
    id: 58,
    name: "Dr. Oğuz Akın",
    name_ar: "د. أوغوز أكن",
    name_tr: "Dr. Oğuz Akın",
    department: "Digital Media",
    department_ar: "الإعلام الرقمي",
    department_tr: "Dijital Medya",
    faculty: "Communication Faculty",
    faculty_ar: "كلية الاتصال",
    faculty_tr: "İletişim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "3",
    room: "315",
    office_hours: "Wed–Fri 14:00–16:00",
    email: "oguz.akin@neu.edu.tr",
    phone: "+90 392 223 6057",
  },
  {
    id: 59,
    name: "Dr. Gül Avcı",
    name_ar: "د. غول أفجي",
    name_tr: "Dr. Gül Avcı",
    department: "Tourism Management",
    department_ar: "إدارة السياحة",
    department_tr: "Turizm İşletmeciliği",
    faculty: "Tourism Faculty",
    faculty_ar: "كلية السياحة",
    faculty_tr: "Turizm Fakültesi",
    building: "Economics Faculty",
    floor: "1",
    room: "125",
    office_hours: "Mon–Thu 11:00–13:00",
    email: "gul.avci@neu.edu.tr",
    phone: "+90 392 223 6058",
  },
  {
    id: 60,
    name: "Dr. Mete Yalçın",
    name_ar: "د. ميتي يالتشن",
    name_tr: "Dr. Mete Yalçın",
    department: "Hotel Management",
    department_ar: "إدارة الفنادق",
    department_tr: "Otel Yönetimi",
    faculty: "Tourism Faculty",
    faculty_ar: "كلية السياحة",
    faculty_tr: "Turizm Fakültesi",
    building: "Economics Faculty",
    floor: "2",
    room: "215",
    office_hours: "Tue–Fri 09:00–11:00",
    email: "mete.yalcin@neu.edu.tr",
    phone: "+90 392 223 6059",
  },
  {
    id: 61,
    name: "Dr. Pelin Korkmaz",
    name_ar: "د. بيلين كوركماز",
    name_tr: "Dr. Pelin Korkmaz",
    department: "Gastronomy",
    department_ar: "فن الطهو",
    department_tr: "Gastronomi",
    faculty: "Tourism Faculty",
    faculty_ar: "كلية السياحة",
    faculty_tr: "Turizm Fakültesi",
    building: "Economics Faculty",
    floor: "1",
    room: "118",
    office_hours: "Mon–Wed 14:00–16:00",
    email: "pelin.korkmaz@neu.edu.tr",
    phone: "+90 392 223 6060",
  },
  {
    id: 62,
    name: "Dr. Nurcan Yıldırım",
    name_ar: "د. نورجان يلدرم",
    name_tr: "Dr. Nurcan Yıldırım",
    department: "Elementary Education",
    department_ar: "التعليم الابتدائي",
    department_tr: "Sınıf Öğretmenliği",
    faculty: "Education Faculty",
    faculty_ar: "كلية التربية",
    faculty_tr: "Eğitim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "2",
    room: "235",
    office_hours: "Mon–Thu 10:00–12:00",
    email: "nurcan.yildirim@neu.edu.tr",
    phone: "+90 392 223 6061",
  },
  {
    id: 63,
    name: "Dr. Serdar Kaya",
    name_ar: "د. سيردار كايا",
    name_tr: "Dr. Serdar Kaya",
    department: "Educational Sciences",
    department_ar: "العلوم التربوية",
    department_tr: "Eğitim Bilimleri",
    faculty: "Education Faculty",
    faculty_ar: "كلية التربية",
    faculty_tr: "Eğitim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "3",
    room: "318",
    office_hours: "Tue–Fri 11:00–13:00",
    email: "serdar.kaya@neu.edu.tr",
    phone: "+90 392 223 6062",
  },
  {
    id: 64,
    name: "Dr. Özlem Cansız",
    name_ar: "د. أوزليم جانسز",
    name_tr: "Dr. Özlem Cansız",
    department: "Preschool Education",
    department_ar: "تعليم ما قبل المدرسة",
    department_tr: "Okul Öncesi Eğitimi",
    faculty: "Education Faculty",
    faculty_ar: "كلية التربية",
    faculty_tr: "Eğitim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "1",
    room: "140",
    office_hours: "Mon–Wed 13:00–15:00",
    email: "ozlem.cansiz@neu.edu.tr",
    phone: "+90 392 223 6063",
  },
  {
    id: 65,
    name: "Dr. Hüseyin Tan",
    name_ar: "د. حسين تان",
    name_tr: "Dr. Hüseyin Tan",
    department: "Mathematics Education",
    department_ar: "تعليم الرياضيات",
    department_tr: "Matematik Öğretmenliği",
    faculty: "Education Faculty",
    faculty_ar: "كلية التربية",
    faculty_tr: "Eğitim Fakültesi",
    building: "Arts & Sciences Faculty",
    floor: "2",
    room: "222",
    office_hours: "Wed–Fri 09:00–11:00",
    email: "huseyin.tan@neu.edu.tr",
    phone: "+90 392 223 6064",
  },
  {
    id: 66,
    name: "Dr. Melis Öztürk",
    name_ar: "د. ميليس أوزتورك",
    name_tr: "Dr. Melis Öztürk",
    department: "Graphic Design",
    department_ar: "التصميم الجرافيكي",
    department_tr: "Grafik Tasarım",
    faculty: "Fine Arts Faculty",
    faculty_ar: "كلية الفنون الجميلة",
    faculty_tr: "Güzel Sanatlar Fakültesi",
    building: "Architecture Faculty",
    floor: "1",
    room: "105",
    office_hours: "Mon–Thu 14:00–16:00",
    email: "melis.ozturk@neu.edu.tr",
    phone: "+90 392 223 6065",
  },
  {
    id: 67,
    name: "Dr. Can Yıldırım",
    name_ar: "د. جان يلدرم",
    name_tr: "Dr. Can Yıldırım",
    department: "Music",
    department_ar: "الموسيقى",
    department_tr: "Müzik",
    faculty: "Fine Arts Faculty",
    faculty_ar: "كلية الفنون الجميلة",
    faculty_tr: "Güzel Sanatlar Fakültesi",
    building: "Architecture Faculty",
    floor: "2",
    room: "218",
    office_hours: "Tue–Fri 10:00–12:00",
    email: "can.yildirim@neu.edu.tr",
    phone: "+90 392 223 6066",
  },
  {
    id: 68,
    name: "Dr. Aslı Korkut",
    name_ar: "د. أسلي كوركوت",
    name_tr: "Dr. Aslı Korkut",
    department: "Photography",
    department_ar: "التصوير الفوتوغرافي",
    department_tr: "Fotoğrafçılık",
    faculty: "Fine Arts Faculty",
    faculty_ar: "كلية الفنون الجميلة",
    faculty_tr: "Güzel Sanatlar Fakültesi",
    building: "Architecture Faculty",
    floor: "3",
    room: "312",
    office_hours: "Mon–Wed 11:00–13:00",
    email: "asli.korkut@neu.edu.tr",
    phone: "+90 392 223 6067",
  },
  {
    id: 69,
    name: "Dr. Koray Yavuz",
    name_ar: "د. كوراي يافوز",
    name_tr: "Dr. Koray Yavuz",
    department: "Industrial Design",
    department_ar: "التصميم الصناعي",
    department_tr: "Endüstriyel Tasarım",
    faculty: "Fine Arts Faculty",
    faculty_ar: "كلية الفنون الجميلة",
    faculty_tr: "Güzel Sanatlar Fakültesi",
    building: "Architecture Faculty",
    floor: "2",
    room: "205",
    office_hours: "Wed–Fri 13:00–15:00",
    email: "koray.yavuz@neu.edu.tr",
    phone: "+90 392 223 6068",
  },
  {
    id: 70,
    name: "Dr. Damla Şahin",
    name_ar: "د. داملا شاهين",
    name_tr: "Dr. Damla Şahin",
    department: "Visual Communication",
    department_ar: "الاتصال البصري",
    department_tr: "Görsel İletişim",
    faculty: "Fine Arts Faculty",
    faculty_ar: "كلية الفنون الجميلة",
    faculty_tr: "Güzel Sanatlar Fakültesi",
    building: "Architecture Faculty",
    floor: "1",
    room: "120",
    office_hours: "Mon–Thu 09:00–11:00",
    email: "damla.sahin@neu.edu.tr",
    phone: "+90 392 223 6069",
  },
]

export const buildings: Building[] = [
  {
    id: "engineering",
    name: "Engineering Faculty",
    type: "academic",
    location: "Central Campus",
    floors: 5,
    hours: "08:00-20:00",
    departments: ["Computer Engineering", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering"],
    description: "Main engineering building with state-of-the-art labs and classrooms",
    gridPosition: { colStart: 1, rowStart: 1, colSpan: 3, rowSpan: 2 },
    color: "bg-red-100",
    icon: "⚙️",
  },
  {
    id: "medicine",
    name: "Medicine Faculty",
    type: "academic",
    location: "Medical Campus",
    floors: 6,
    hours: "08:00-18:00",
    departments: ["Medicine", "Dentistry", "Pharmacy"],
    description: "Modern medical education facility",
    gridPosition: { colStart: 4, rowStart: 1, colSpan: 3, rowSpan: 2 },
    color: "bg-blue-100",
    icon: "🏥",
  },
  {
    id: "library",
    name: "Grand Library",
    type: "library",
    location: "Central Campus",
    floors: 7,
    hours: "24/7",
    departments: ["Main Library", "Study Areas", "Computer Labs"],
    description: "7-floor library with 24/7 access",
    gridPosition: { colStart: 7, rowStart: 1, colSpan: 3, rowSpan: 2 },
    color: "bg-green-100",
    icon: "📚",
  },
  {
    id: "dormitory",
    name: "Student Dormitory",
    type: "residential",
    location: "East Campus",
    floors: 10,
    hours: "24/7",
    departments: ["Student Housing"],
    description: "Modern student accommodation",
    gridPosition: { colStart: 10, rowStart: 1, colSpan: 3, rowSpan: 2 },
    color: "bg-purple-100",
    icon: "🏠",
  },
  {
    id: "sports",
    name: "Sports Complex",
    type: "sports",
    location: "East Campus",
    floors: 3,
    hours: "06:00-23:00",
    departments: ["Gym", "Swimming Pool", "Sports Courts"],
    description: "Full sports and fitness facilities",
    gridPosition: { colStart: 1, rowStart: 3, colSpan: 3, rowSpan: 2 },
    color: "bg-yellow-100",
    icon: "⚽",
  },
  {
    id: "architecture",
    name: "Architecture Faculty",
    type: "academic",
    location: "West Campus",
    floors: 4,
    hours: "08:00-20:00",
    departments: ["Architecture", "Urban Design", "Interior Design"],
    description: "Architecture and design studios",
    gridPosition: { colStart: 4, rowStart: 3, colSpan: 3, rowSpan: 2 },
    color: "bg-red-100",
    icon: "📐",
  },
  {
    id: "hospital",
    name: "NEU Hospital",
    type: "medical",
    location: "Medical Campus",
    floors: 8,
    hours: "24/7 Emergency",
    departments: ["Emergency", "Surgery", "Outpatient Clinics"],
    description: "Full-service teaching hospital",
    gridPosition: { colStart: 7, rowStart: 3, colSpan: 3, rowSpan: 2 },
    color: "bg-blue-100",
    icon: "🚑",
  },
  {
    id: "admin",
    name: "Administration Building",
    type: "administrative",
    location: "Central Campus",
    floors: 4,
    hours: "08:00-17:00",
    departments: ["Administration", "Finance", "Student Affairs"],
    description: "Main administrative offices",
    gridPosition: { colStart: 10, rowStart: 3, colSpan: 3, rowSpan: 2 },
    color: "bg-green-100",
    icon: "🏛️",
  },
  {
    id: "cafeteria",
    name: "Central Cafeteria",
    type: "food",
    location: "Central Campus",
    floors: 2,
    hours: "08:00-22:00",
    departments: ["Main Dining", "Coffee Shop"],
    description: "Main dining facility",
    gridPosition: { colStart: 1, rowStart: 5, colSpan: 3, rowSpan: 2 },
    color: "bg-purple-100",
    icon: "🍽️",
  },
  {
    id: "arts",
    name: "Arts & Sciences Faculty",
    type: "academic",
    location: "Central Campus",
    floors: 5,
    hours: "08:00-20:00",
    departments: ["Psychology", "Mathematics", "Physics", "Chemistry"],
    description: "Liberal arts and sciences",
    gridPosition: { colStart: 4, rowStart: 5, colSpan: 3, rowSpan: 2 },
    color: "bg-yellow-100",
    icon: "🎨",
  },
  {
    id: "law",
    name: "Law Faculty",
    type: "academic",
    location: "West Campus",
    floors: 4,
    hours: "08:00-18:00",
    departments: ["Law", "International Relations"],
    description: "Law school and moot courts",
    gridPosition: { colStart: 7, rowStart: 5, colSpan: 3, rowSpan: 2 },
    color: "bg-red-100",
    icon: "⚖️",
  },
  {
    id: "pharmacy",
    name: "Pharmacy Faculty",
    type: "academic",
    location: "Medical Campus",
    floors: 4,
    hours: "08:00-18:00",
    departments: ["Pharmacy", "Pharmaceutical Sciences"],
    description: "Pharmacy education and research",
    gridPosition: { colStart: 10, rowStart: 5, colSpan: 3, rowSpan: 2 },
    color: "bg-blue-100",
    icon: "💊",
  },
]

export const facilities: Facility[] = [
  {
    id: 1,
    name: "Grand Library",
    type: "library",
    location: "Central Campus",
    hours: "24/7",
    description: "7 floors, 24/7 access, study areas, computer labs",
  },
  {
    id: 2,
    name: "Central Cafeteria",
    type: "restaurant",
    location: "Main Campus",
    hours: "08:00-22:00",
    description: "Main dining area with multiple food options",
  },
  {
    id: 3,
    name: "Sports Complex",
    type: "sports",
    location: "East Campus",
    hours: "06:00-23:00",
    description: "Gym, swimming pool, basketball courts, tennis courts",
  },
  {
    id: 4,
    name: "NEU Hospital",
    type: "medical",
    location: "Medical Campus",
    hours: "24/7 Emergency",
    description: "Full-service hospital with emergency department",
  },
  {
    id: 5,
    name: "Student Center",
    type: "student services",
    location: "Central Campus",
    hours: "08:00-22:00",
    description: "Student clubs, activities, and social spaces",
  },
]
