export interface AcademicCourse {
  code: string
  name: string
  credits: number
  ects: number
  theory: number
  lab: number
  prerequisite?: string
  description: string
  semester: string // e.g., "1st Year Fall", "2nd Year Spring"
  year: number
  semesterNumber: number // 1-8
  type: "required" | "elective" | "technical-elective" | "non-technical-elective"
  program: "SWE" | "MIS"
}

export interface ProgramRequirements {
  program: string
  totalCredits: number
  totalECTS: number
  requiredCourses: number
  electiveCourses: number
  technicalElectives: number
  minGPA: number
  summerPractice: number
  graduationProject: boolean
  description: string
}

// SOFTWARE ENGINEERING PROGRAM - From Official PDF
export const sweCourses: AcademicCourse[] = [
  // YEAR 1 - SEMESTER 1 (FALL)
  {
    code: "CHM101",
    name: "General Chemistry",
    credits: 4,
    ects: 5,
    theory: 4,
    lab: 2,
    description: "Basic concepts of chemistry, atomic theory, stoichiometry, periodic relationships, chemical bonding.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "SWE",
  },
  {
    code: "ENG101",
    name: "English I",
    credits: 3,
    ects: 3,
    theory: 3,
    lab: 0,
    description:
      "Intermediate English with grammatical structures and vocabulary to build foundation for university studies.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "SWE",
  },
  {
    code: "PHY101",
    name: "General Physics I",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 2,
    description: "Measurement, vectors, kinematics, force, Newton's laws, work and energy, momentum, rotation.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "SWE",
  },
  {
    code: "MTH101",
    name: "Mathematics I (Calculus I)",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 0,
    description:
      "Functions, limits, derivatives, integration, applications of calculus, exponential and logarithmic functions.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "SWE",
  },
  {
    code: "MTH113",
    name: "Linear Algebra",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description: "Systems of linear equations, matrices, determinants, vector spaces, eigenvalues and eigenvectors.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC102",
    name: "Programming and Problem Solving",
    credits: 4,
    ects: 5,
    theory: 4,
    lab: 2,
    description:
      "Introduction to programming using Python, data structures, functions, iteration, recursion, object-oriented basics.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "SWE",
  },

  // YEAR 1 - SEMESTER 2 (SPRING)
  {
    code: "ECC108",
    name: "Object Oriented Programming",
    credits: 3,
    ects: 6,
    theory: 4,
    lab: 2,
    prerequisite: "ECC102",
    description:
      "In-depth object-oriented programming using Python 3, advanced programming concepts and design patterns.",
    semester: "1st Year Spring",
    year: 1,
    semesterNumber: 2,
    type: "required",
    program: "SWE",
  },
  {
    code: "ENG102",
    name: "English II",
    credits: 3,
    ects: 3,
    theory: 3,
    lab: 0,
    prerequisite: "ENG101",
    description: "Advanced English with technical vocabulary, business communication, and presentation skills.",
    semester: "1st Year Spring",
    year: 1,
    semesterNumber: 2,
    type: "required",
    program: "SWE",
  },
  {
    code: "MTH102",
    name: "Mathematics II (Calculus II)",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 0,
    prerequisite: "MTH101",
    description:
      "Multivariable calculus, partial derivatives, multiple integrals, sequences and series, Taylor series.",
    semester: "1st Year Spring",
    year: 1,
    semesterNumber: 2,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC104",
    name: "Discrete Structures",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Sets, logic, proofs, functions, algorithms, graph theory, Boolean algebras, automata.",
    semester: "1st Year Spring",
    year: 1,
    semesterNumber: 2,
    type: "required",
    program: "SWE",
  },
  {
    code: "PHY102",
    name: "General Physics II",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 2,
    prerequisite: "PHY101",
    description:
      "Electrical charges, electric fields, Gauss's law, capacitance, current, magnetic fields, Faraday's law.",
    semester: "1st Year Spring",
    year: 1,
    semesterNumber: 2,
    type: "required",
    program: "SWE",
  },

  // YEAR 2 - SEMESTER 3 (FALL)
  {
    code: "ECC201",
    name: "Data Structures and Algorithms",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 2,
    prerequisite: "ECC108",
    description:
      "Abstract data types, algorithm design and complexity analysis using Python and object-oriented programming.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC001",
    name: "Logic Design",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 2,
    prerequisite: "ECC104",
    description: "Digital systems, combinational and sequential circuits, HDLs, computer design basics, RISC and CISC.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "SWE",
  },
  {
    code: "MTH251",
    name: "Probability and Statistics",
    credits: 3,
    ects: 6,
    theory: 4,
    lab: 0,
    prerequisite: "MTH113",
    description: "Probability models, random variables, distributions, statistical inference, regression analysis.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC427",
    name: "Management for Engineers",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description:
      "Principles of management, organizational functions, marketing, production, personnel, financial control.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC003",
    name: "Software Engineering",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    prerequisite: "ECC104",
    description: "Software engineering principles, requirements, design, testing, UML, object orientation, frameworks.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "SWE",
  },

  // YEAR 2 - SEMESTER 4 (SPRING)
  {
    code: "ECC202",
    name: "Database Management Systems",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 0,
    prerequisite: "ECC201",
    description:
      "Database architecture, relational model, SQL, conceptual modeling, normalization, query processing, transactions.",
    semester: "2nd Year Spring",
    year: 2,
    semesterNumber: 4,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC203",
    name: "Computer Architecture and Organisation",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    prerequisite: "ECC001",
    description:
      "Computer hardware structure, micro-programming, memory organization, I/O systems, RISC, pipeline, vector computers.",
    semester: "2nd Year Spring",
    year: 2,
    semesterNumber: 4,
    type: "required",
    program: "SWE",
  },
  {
    code: "ENG201",
    name: "Technical Report Writing and Presentation",
    credits: 3,
    ects: 3,
    theory: 3,
    lab: 0,
    prerequisite: "ENG102",
    description:
      "Critical technical writing and presentation skills, language reinforcement, professional communication.",
    semester: "2nd Year Spring",
    year: 2,
    semesterNumber: 4,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE202",
    name: "Software Construction",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    prerequisite: "ECC003",
    description:
      "Low-level software design, grammars, parsers, formal methods, concurrency, middleware, performance tuning.",
    semester: "2nd Year Spring",
    year: 2,
    semesterNumber: 4,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE234",
    name: "Human-Computer Interaction",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description:
      "Human cognition principles, usability engineering, task analysis, user-centred design, interface evaluation.",
    semester: "2nd Year Spring",
    year: 2,
    semesterNumber: 4,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE299",
    name: "Summer Practice I",
    credits: 0,
    ects: 2,
    theory: 0,
    lab: 0,
    description: "40 working days minimum in manufacturing or service organization to apply theoretical knowledge.",
    semester: "Summer after 2nd Year",
    year: 2,
    semesterNumber: 4,
    type: "required",
    program: "SWE",
  },

  // YEAR 3 - SEMESTER 5 (FALL)
  {
    code: "ECC302",
    name: "Operating Systems",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    prerequisite: "ECC201",
    description:
      "OS structure and functions, memory management, multiprocessing, virtual memory, scheduling, deadlocks, file systems.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC004",
    name: "Programming Languages I",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 2,
    prerequisite: "ECC201",
    description: "Overview of programming language concepts, Visual Basic components, event-driven programming.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE301",
    name: "Software Design and Architecture",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 0,
    prerequisite: "SWE202",
    description:
      "Software design concepts, design patterns, frameworks, architectures, middleware, component-based design, metrics.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC311",
    name: "Management Information Systems",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 0,
    prerequisite: "ECC427",
    description:
      "MIS roles in business, technology architectures, functional information systems, decision support, knowledge management.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "SWE",
  },

  // YEAR 3 - SEMESTER 6 (SPRING)
  {
    code: "ECC005",
    name: "Internet Programming",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 1,
    prerequisite: "ECC004",
    description:
      "Internet concepts, HTML, GUI design, ASP for web applications, uploading and testing internet applications.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC303",
    name: "Data Communication and Networking",
    credits: 4,
    ects: 6,
    theory: 4,
    lab: 1,
    prerequisite: "ECC001",
    description:
      "Network design, IP protocols, internet suite, multimedia, wireless communications, LAN, WAN, network security.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "SWE",
  },
  {
    code: "ECC426",
    name: "Economics for Engineers",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description:
      "Economic analysis of engineering decisions, cost concepts, make-versus-purchase, money-time relations, depreciation.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE302",
    name: "Software Quality Assurance and Testing",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    prerequisite: "SWE301",
    description:
      "Quality assurance, verification and validation, testing techniques, inspections, process and product assurance.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE304",
    name: "Software Requirements Analysis",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    prerequisite: "SWE301",
    description:
      "Requirements discovery and elicitation, modeling, analysis, validation, domain engineering, traceability, requirements management.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE399",
    name: "Summer Practice II",
    credits: 0,
    ects: 2,
    theory: 0,
    lab: 0,
    prerequisite: "SWE299",
    description: "Second 40-day summer practice in industry to further develop professional skills.",
    semester: "Summer after 3rd Year",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "SWE",
  },

  // YEAR 4 - SEMESTER 7 (FALL)
  {
    code: "ECC430",
    name: "Principles of Information Security",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    prerequisite: "ECC303",
    description:
      "Information security themes and principles, risk management, security planning, cryptography, physical security.",
    semester: "4th Year Fall",
    year: 4,
    semesterNumber: 7,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE401",
    name: "Software Project Management",
    credits: 3,
    ects: 4,
    theory: 3,
    lab: 0,
    prerequisite: "SWE304",
    description:
      "Project planning, cost estimation, scheduling, productivity metrics, risk analysis, configuration management, software contracts.",
    semester: "4th Year Fall",
    year: 4,
    semesterNumber: 7,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE491",
    name: "Graduation Project I",
    credits: 4,
    ects: 6,
    theory: 2,
    lab: 2,
    description:
      "Individual scientific research project to apply technical knowledge and develop professional abilities.",
    semester: "4th Year Fall",
    year: 4,
    semesterNumber: 7,
    type: "required",
    program: "SWE",
  },

  // YEAR 4 - SEMESTER 8 (SPRING)
  {
    code: "ECC429",
    name: "Engineering Ethics",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "International political economy, mercantilism, liberalism, structuralism, trade, finance, global problems.",
    semester: "4th Year Spring",
    year: 4,
    semesterNumber: 8,
    type: "required",
    program: "SWE",
  },
  {
    code: "SWE492",
    name: "Graduation Project II",
    credits: 4,
    ects: 8,
    theory: 4,
    lab: 2,
    prerequisite: "SWE491",
    description: "Continuation of Graduation Project with oral presentations and written technical reports.",
    semester: "4th Year Spring",
    year: 4,
    semesterNumber: 8,
    type: "required",
    program: "SWE",
  },

  // TECHNICAL ELECTIVES
  {
    code: "ECC431",
    name: "e-Commerce",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 2,
    description: "Electronic commerce concepts, online business models, payment systems, security in e-commerce.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
  {
    code: "ECC412",
    name: "Database Applications",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 2,
    prerequisite: "ECC202",
    description: "Advanced database programming, stored procedures, triggers, database application development.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
  {
    code: "ECC404",
    name: "Neural Networks",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 2,
    description: "Neural network paradigm, back propagation, feedback networks, Hopfield networks, genetic algorithms.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
  {
    code: "ECC406",
    name: "System Programming",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 2,
    description: "Operating system kernel routines, low-level programming, memory management, threads, file systems.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
  {
    code: "ECC417",
    name: "Mobile Programming",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description:
      "Mobile application development, iOS and Android platforms, mobile UI design, sensors and location services.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
  {
    code: "SWE403",
    name: "Large Scale Software Development",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description:
      "Large-scale software lifecycle, software architecture, component design, subsystem design, deployment design.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
  {
    code: "SWE404",
    name: "Software Patterns",
    credits: 3,
    ects: 5,
    theory: 3,
    lab: 0,
    description:
      "Design patterns, creational patterns, structural patterns, behavioral patterns, analysis patterns, refactoring.",
    semester: "Elective",
    year: 4,
    semesterNumber: 0,
    type: "technical-elective",
    program: "SWE",
  },
]

// MANAGEMENT INFORMATION SYSTEMS PROGRAM - From Official PDF
export const misCourses: AcademicCourse[] = [
  {
    code: "ENG101",
    name: "English I",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Grammar development and language skills for understanding lessons and expressing in English.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAT171",
    name: "Mathematics for Business and Economics I",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Business calculus and financial mathematics, solving business problems independently.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "MIS",
  },
  {
    code: "COM151",
    name: "Introduction to Computers",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Computer history, generations, hardware, classification, MS-DOS operating system, DOS editor.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAN101",
    name: "Introduction to Business",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Functional areas of business: finance, HR, management sciences, information systems, marketing.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "MIS",
  },
  {
    code: "ECON101",
    name: "Principles of Economics I (Microeconomics)",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Basic economics concepts, supply and demand, elasticity, consumer and firm behavior, market analysis.",
    semester: "1st Year Fall",
    year: 1,
    semesterNumber: 1,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAN201",
    name: "Business Communication",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "English grammar and vocabulary in business context, communication skills improvement.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAT281",
    name: "Statistics I",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Frequency distributions, central tendency, dispersion, probability, probability distributions, sampling.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "MIS",
  },
  {
    code: "ACC202",
    name: "Financial Accounting I",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Accounting for decision making, financial statements, accounting cycle, accruals, deferrals, merchandising.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAN206",
    name: "Introduction to Law",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Nature of law, legal systems, development of law, court structure, legal personality, European Union law.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "MIS",
  },
  {
    code: "ECON201",
    name: "Microeconomics",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Firm and industry, perfect competition, monopoly, oligopoly, factors of production, game theory.",
    semester: "2nd Year Fall",
    year: 2,
    semesterNumber: 3,
    type: "required",
    program: "MIS",
  },
  {
    code: "MARK303",
    name: "Principles of Marketing",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Fundamental marketing concepts, business activities, systems perspective, planning, pricing, promoting, distributing.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS301",
    name: "Information System Management",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Management of hardware, software, personnel. Planning, developing, installing, operating information systems.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "MIS",
  },
  {
    code: "FIN301",
    name: "Business Finance",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Cash flow analysis, financial statement analysis, time value of money, valuation, capital budgeting.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAN310",
    name: "Organizational Behavior",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Behavioral sciences in management, communication, motivation, conflict, decision-making, leadership, organizational design.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "MIS",
  },
  {
    code: "ECON306",
    name: "Money and Banking",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Financial intermediation, interest rates, banking, monetary policy, asset prices, inflation, exchange rates.",
    semester: "3rd Year Fall",
    year: 3,
    semesterNumber: 5,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS302",
    name: "Quantitative Analysis for Decision Making",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Mathematical tools for business, decision theory, linear programming, queuing, network analysis, simulation.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "MIS",
  },
  {
    code: "EAS307",
    name: "Research Methods",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Professional communication, research, critical reading and thinking, analysis, interpretation, oral and written presentations.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "MIS",
  },
  {
    code: "FIN302",
    name: "Financial Management",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Risk and return, cost of capital, capital structure, dividends and dividend policy, financial planning.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "MIS",
  },
  {
    code: "MAN308",
    name: "Operations Management & Research",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Operations management principles, process design, capacity planning, inventory management, quality control.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS303",
    name: "Information System Project Management",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Project management principles, IS development, project planning, team design, estimation, risk control, quality assurance.",
    semester: "3rd Year Spring",
    year: 3,
    semesterNumber: 6,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS401",
    name: "E-Business Management",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "E-business concepts, strategic management, e-business models, electronic marketing, customer relationship management.",
    semester: "4th Year Fall",
    year: 4,
    semesterNumber: 7,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS421",
    name: "System Analysis and Design",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Systems development lifecycle, analysis, design, development, implementation, evaluation, project management.",
    semester: "4th Year Fall",
    year: 4,
    semesterNumber: 7,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS422",
    name: "Entrepreneurship in Information Technology",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description:
      "Startup process, opportunity analysis, market identification, competition, success factors, technology and processes.",
    semester: "4th Year Spring",
    year: 4,
    semesterNumber: 8,
    type: "required",
    program: "MIS",
  },
  {
    code: "MIS400",
    name: "Final Project",
    credits: 3,
    ects: 6,
    theory: 3,
    lab: 0,
    description: "Software development project to be completed in one semester.",
    semester: "4th Year Spring",
    year: 4,
    semesterNumber: 8,
    type: "required",
    program: "MIS",
  },
]

export const programRequirements: ProgramRequirements[] = [
  {
    program: "Software Engineering",
    totalCredits: 142,
    totalECTS: 240,
    requiredCourses: 51,
    electiveCourses: 10,
    technicalElectives: 5,
    minGPA: 2.0,
    summerPractice: 2,
    graduationProject: true,
    description:
      "The undergraduate program in Software Engineering consists of 51 courses with 255 ECTS credits in total. Students must complete required courses, technical electives, and two summer training periods.",
  },
  {
    program: "Management Information Systems",
    totalCredits: 120,
    totalECTS: 240,
    requiredCourses: 40,
    electiveCourses: 10,
    technicalElectives: 5,
    minGPA: 2.0,
    summerPractice: 0,
    graduationProject: true,
    description:
      "The undergraduate program in Management Information Systems consists of 120 credits with 240 ECTS. Students study business, management, and information technology integration.",
  },
]

export const allAcademicCourses = [...sweCourses, ...misCourses]

// Helper functions
export function getCoursesByProgram(program: "SWE" | "MIS") {
  return allAcademicCourses.filter((course) => course.program === program)
}

export function getCoursesBySemester(program: "SWE" | "MIS", semesterNumber: number) {
  return allAcademicCourses.filter((course) => course.program === program && course.semesterNumber === semesterNumber)
}

export function searchCourses(query: string) {
  const lowerQuery = query.toLowerCase()
  return allAcademicCourses.filter(
    (course) =>
      course.code.toLowerCase().includes(lowerQuery) ||
      course.name.toLowerCase().includes(lowerQuery) ||
      course.description.toLowerCase().includes(lowerQuery),
  )
}

export function getCoursePrerequisites(courseCode: string): AcademicCourse[] {
  const course = allAcademicCourses.find((c) => c.code === courseCode)
  if (!course || !course.prerequisite) return []

  const prereqCourse = allAcademicCourses.find((c) => c.code === course.prerequisite)
  if (!prereqCourse) return []

  return [prereqCourse, ...getCoursePrerequisites(prereqCourse.code)]
}

export function getCoursesRequiringThis(courseCode: string): AcademicCourse[] {
  return allAcademicCourses.filter((c) => c.prerequisite === courseCode)
}
